### ISSUE TITLE
Flux Spack packages missing checksums

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [flux-framework/flux-docs#239] opened 2023-05-09 15:48 UTC
Spack can't seem to find checksums for versions (`0.49.0` and `0.27.0`) of flux-core and flux-sched.  Possibly other versions are also missing Spack checksums.  This results in interactive prompts during Spack installation (or passing `--no-checksum` to `spack install`) which interferes with unattended installations.  Is it possible to update the Spack packages to make sure checksums are included for all versions?

**Comment by christopherwharrop-noaa** [comment] 2023-05-09 16:01
I did post a question about this in the Spack Slack space, but it did not fetch a response.  If this was the wrong place to report this, I apologize.  Please feel free to close and move to the correct forum.

**Comment by vsoch** [comment] 2023-05-09 17:42
@christopherwharrop-noaa I used to work on spack a bit - let me pull the current develop and see if I can reproduce your issue.

**Comment by vsoch** [comment] 2023-05-09 17:45
Confirmed both have checksums in the package.py files - although that doesn't mean spack is using them correctly! I'm doing an install of flux-core 0.49.0 and will see what I get.

**Comment by vsoch** [comment] 2023-05-09 18:04
@christopherwharrop-noaa while we are waiting could you show me the full error message about the checksums with —debug, your version of Spack and install command?

**Comment by christopherwharrop-noaa** [comment] 2023-05-09 19:19
@vsoch - It will take me some time to rerun it with `--debug`.  I'll start that now.  I am using Spack v0.19.2.  The commands are:

```
# Install flux components
spack add flux-core@0.49.0%gcc@11.2.0 ^python@3.9 target=x86_64
spack add flux-sched@0.27.0%gcc@11.2.0 ^python@3.9 target=x86_64
spack install
```

I can give you the entire script if you need it. This is what I see without using `--debug`

```
==> Installing flux-core-0.49.0-5oa3jvwvflxpkx62pwbpw5vub653h4jq
==> No binary for flux-core-0.49.0-5oa3jvwvflxpkx62pwbpw5vub653h4jq found: installing from source
==> Warning: There is no checksum on file to fetch flux-core@0.49.0 safely.
==>   Fetch anyway? [y/N] y
==> Fetching https://github.com/flux-framework/flux-core/releases/download/v0.49.0/flux-core-0.49.0.tar.gz
==> No patches needed for flux-core
==> flux-core: Executing phase: 'autoreconf'
==> flux-core: Executing phase: 'configure'
==> flux-core: Executing phase: 'build'
==> flux-core: Executing phase: 'install'
==> flux-core: Successfully installed flux-core-0.49.0-5oa3jvwvflxpkx62pwbpw5vub653h4jq
  Fetch: 1.34s.  Build: 12m 24.70s.  Total: 12m 26.04s.
[+] /work/noaa/gsd-hpcs/charrop/opt/spack/opt/spack/[padded-to-128-chars]/linux-centos7-x86_64/gcc-11.2.0/flux-core-0.49.0-5oa3jvwvflxpkx62pwbpw5vub653h4jq
==> Installing flux-sched-0.27.0-nnozznmblhg7bmutiarmq7iua55zm4ag
==> No binary for flux-sched-0.27.0-nnozznmblhg7bmutiarmq7iua55zm4ag found: installing from source
==> Warning: There is no checksum on file to fetch flux-sched@0.27.0 safely.
==>   Fetch anyway? [y/N] y
==> Fetching https://github.com/flux-framework/flux-sched/releases/download/v0.27.0/flux-sched-0.27.0.tar.gz
==> No patches needed for flux-sched
==> flux-sched: Executing phase: 'autoreconf'
==> flux-sched: Executing phase: 'configure'
==> flux-sched: Executing phase: 'build'
==> flux-sched: Executing phase: 'install'
==> flux-sched: Successfully installed flux-sched-0.27.0-nnozznmblhg7bmutiarmq7iua55zm4ag
  Fetch: 1.31s.  Build: 6m 23.69s.  Total: 6m 25.00s.
[+] /work/noaa/gsd-hpcs/charrop/opt/spack/opt/spack/[padded-to-128-chars]/linux-centos7-x86_64/gcc-11.2.0/flux-sched-0.27.0-nnozznmblhg7bmutiarmq7iua55zm4ag
```

**Comment by vsoch** [comment] 2023-05-09 19:23
@christopherwharrop-noaa I can't reproduce - so likely it's something niche about your spack version / environment. I'm not a spack developer (and this particular issue board is for the flux documentation site) so I'll have to ask that you open an issue on spack https://github.com/spack/spack/issues and feel free to ping me so I can follow along and see if there are any updates / triage needed for our packages. I can't transfer this issue there so I'm going to close it - but when you re-open there I'd recommend including:

1. The version of spack, your operating system and general environment
2. The exact command you ran
3. The console output that was shown that is concerning

Spack has had several bugs with these checksum flags over time, and (unfortunately) given the quickly changing solver and dependencies chosen for any install command, weird / spurious errors tend to come up. As long as you can provide enough information for someone to reproduce your issue they should be able to help. See you on the other board!

**Closed by vsoch** 2023-05-09 19:23 UTC

**Comment by vsoch** [comment] 2023-05-09 19:27
And @christopherwharrop-noaa I think I suspect that I know the problem - I remember when I went back to an old release of spack the if statement that would result in that message had a bug, and it would trigger in a case that wasn't warranted. So if you are able, try updating the spack version too. And from the above it looks like you are working from an environment? Make sure to include your spack.yaml there too (or the full commands starting from scratch).

**Comment by vsoch** [comment] 2023-05-09 19:30
Found it - here is the bug (I had to fix it manually using an older spack for one of our builds) - https://github.com/flux-framework/spack/commit/4e9c4fdec9bccc0abcd6c0feb062016fbe89eb1d#diff-2976edab4b3cfd92ca9323e10bdfc8b50069d6dca45eb15224711d61abde62a3

It's hitting that because of the tty variable, and it has nothing to do with the checksum, at least if this is the version you are using. If it's not, then there is some new bug that the devs will have to help with. Sorry I can't help more!

**Comment by christopherwharrop-noaa** [comment] 2023-05-09 20:04
@vsoch - Thank you for all the great pointers where to look.  I'm sorry if I wasted your time here.  Not knowing a ton about Spack or Flux I wasn't sure where the issue should be reported.  I appreciate your assistance in pointing me in the right direction.

**Comment by vsoch** [comment] 2023-05-09 20:18
@christopherwharrop-noaa it is never a waste of time to help someone! I think we are a bit limited here, but I wanted to point you to the right place to get help, offer to follow along in case work is needed on our packages, and give as might insight as I might have.

And are you at NOAA? You are down the street from me - in dinosaur country! 🎉 ⛰️ I like going on the trails you can reach from the neighborhoods behind you.

**Comment by grondo** [comment] 2023-05-09 21:09
Great work @vsoch!

@christopherwharrop-noaa feel free to open issues at https://github.com/flux-framework/flux-core/issues or Q&A type questions on the DIscussions area at https://github.com/flux-framework/flux-core/discussions. We'll be happy to help and pleased to meet you. Good luck!
